FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git curl

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

COPY ./api-gateway/go.mod ./api-gateway/go.sum ./
RUN go mod download

COPY ./api-gateway .

EXPOSE 8080

CMD ["air"]
