FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git curl

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

COPY ./message-service/go.mod ./message-service/go.sum ./
RUN go mod download

COPY ./message-service .

EXPOSE 8085

CMD ["air"]
