###
POST http://localhost:8081/register
Content-Type: application/json

{
    "username": "hello",
    "email": "sourva55@gmail.com",
    "password": "1234@Joy"
}

### 
POST http://localhost:8081/login
Content-Type: application/json

{
    "username": "test2",
    "password": "1234@Joy"
}

### 
POST http://localhost:8081/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIwNTAwMDQsImlhdCI6MTc0MjA0OTEwNCwiaXNzIjoiaWRlbnRpdHlfc2VydmljZSIsImp0aSI6IjMxZDYyNzI3LTY2MDYtNGY3Zi1hOTg1LTYxOWRmNTVhYmUzMSIsIm5iZiI6MTc0MjA0OTEwNCwic3ViIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIiwidXNlcl9pZCI6IjAxOTU5NGM1LTFjNWUtN2QyMS05ZTRhLTk5ZDU1YTU2YzI2YSJ9.tzwn145xqjLTMPJxeVSUzRd15iVxQoNWrRVP0XmXrTw

{
    "user_id": "019594c5-1c5e-7d21-9e4a-99d55a56c26a"
}


###
GET http://localhost:8081/user/test2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI2NTM5MTksImlhdCI6MTc0MjA0OTExOSwiaXNzIjoiaWRlbnRpdHlfc2VydmljZSIsImp0aSI6ImIxYTVlOGMwLTc1ZjktNDIyMC04NzE0LTJjYjM3YTNkNjQwYyIsIm5iZiI6MTc0MjA0OTExOSwic3ViIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIiwidHlwZSI6InJlZnJlc2giLCJ1c2VyX2lkIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIn0.6LfYg0hIwDGthmTbl2f46aodWgOnDrlock9ndg8cA04

###
POST http://localhost:8081/refresh-token
Content-Type: application/json

{
"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI2NTQ2NTQsImlhdCI6MTc0MjA0OTg1NCwiaXNzIjoiaWRlbnRpdHlfc2VydmljZSIsImp0aSI6ImZmNmZmNDAzLTlhMzktNDEyMC1hNTFiLWU2ZmQwNTc1Y2IzYiIsIm5iZiI6MTc0MjA0OTg1NCwic3ViIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIiwidHlwZSI6InJlZnJlc2giLCJ1c2VyX2lkIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIn0.ogLkuD1a3-rwqofnDRA5AhCovhvrfhlWJ8tFHq1mnkI"
}

###
POST http://localhost:8081/send-otp
Content-Type: application/json

{
    "email": "sourva55@gmail.com"
}


###
POST http://localhost:8081/verify-otp
Content-Type: application/json

{
    "email": "sourva55@gmail.com",
    "otp": "342279"
}
