
###
get http://localhost:8080/health

###
get http://localhost:8080/v1/auth/health

###
get http://localhost:8081/health

###
POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
    "username": "hello2",
    "email": "sourva55@gmail.com",
    "password": "1234@Joy"
}


###
POST http://localhost:8080/v1/auth/verify-otp
Content-Type: application/json

{
    "email": "sourva55@gmail.com",
    "otp": "726008"
}

### 
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
    "username": "hello",
    "password": "1234@Joy"
}


###
POST http://localhost:8080/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQyMjI5OTksImlhdCI6MTc0NDIyMjA5OSwiaXNzIjoiaWRlbnRpdHktc2VydmljZSIsImp0aSI6IjQ0YTExYjAxLWU3NmUtNDNiMi1hZjcwLTlhNmE3M2MzODcyMCIsIm5iZiI6MTc0NDIyMjA5OSwic3ViIjoiMDE5NjE5YTAtY2JlMC03NWQ1LWI5YWQtNTI1ZjM4MTI2Zjk2IiwidXNlcl9pZCI6IjAxOTYxOWEwLWNiZTAtNzVkNS1iOWFkLTUyNWYzODEyNmY5NiJ9.R5i-7wYeZX3ew1SbbKtSau7XuFSzETrXSPe5SG3YQhA

{
    "user_id": "019619a0-cbe0-75d5-b9ad-525f38126f96"
}



###
GET http://localhost:8081/user/test2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI2NTM5MTksImlhdCI6MTc0MjA0OTExOSwiaXNzIjoiaWRlbnRpdHlfc2VydmljZSIsImp0aSI6ImIxYTVlOGMwLTc1ZjktNDIyMC04NzE0LTJjYjM3YTNkNjQwYyIsIm5iZiI6MTc0MjA0OTExOSwic3ViIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIiwidHlwZSI6InJlZnJlc2giLCJ1c2VyX2lkIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIn0.6LfYg0hIwDGthmTbl2f46aodWgOnDrlock9ndg8cA04

###
POST http://localhost:8081/refresh-token
Content-Type: application/json

{
"refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI2NTQ2NTQsImlhdCI6MTc0MjA0OTg1NCwiaXNzIjoiaWRlbnRpdHlfc2VydmljZSIsImp0aSI6ImZmNmZmNDAzLTlhMzktNDEyMC1hNTFiLWU2ZmQwNTc1Y2IzYiIsIm5iZiI6MTc0MjA0OTg1NCwic3ViIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIiwidHlwZSI6InJlZnJlc2giLCJ1c2VyX2lkIjoiMDE5NTk0YzUtMWM1ZS03ZDIxLTllNGEtOTlkNTVhNTZjMjZhIn0.ogLkuD1a3-rwqofnDRA5AhCovhvrfhlWJ8tFHq1mnkI"
}

###
POST http://localhost:8081/request-otp
Content-Type: application/json

{
    "email": "sourva55@gmail.com"
}


###
POST http://localhost:8081/verify-otp
Content-Type: application/json

{
    "email": "sourva55@gmail.com",
    "otp": "641938"
}


###
get http://localhost:8082/health

###
post http://localhost:8082/check
Content-Type: application/json

{
    "text": "hello0"
}


###
GET http://localhost:8085/ws
Content-Type: application/json

{
    "username": "test",
    "message": "hello"
}

