version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    # volumes:
    #   - ./api_gateway:/app
    env_file:
      - api_gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - image-service
      - word-service
    networks:
      - app-network

  identity-service:
    build:
      context: .
      dockerfile: identity_service/Dockerfile
    # volumes:
    #   - ./identityService:/app
    env_file:
      - identity_service/.env
    ports:
      - "8081:8081"
    networks:
      - app-network

  word-service:
    build:
      context: .
      dockerfile: word_filter_service/Dockerfile
    # volumes:
    #   - ./word_filter_service:/app
    env_file:
      - word_filter_service/.env
    ports:
      - "8082:8082"
    networks:
      - app-network

  image-service:
    build:
      context: .
      dockerfile: image_check/Dockerfile
    env_file:
      - image_check/.env
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
