version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    # volumes:
    #   - ./api-gateway:/app
    env_file:
      - api-gateway/.env
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - image-service
      - word-service
    networks:
      - app-network

  identity-service:
    build:
      context: .
      dockerfile: identityService/Dockerfile
    # volumes:
    #   - ./identityService:/app
    env_file:
      - identityService/.env
    ports:
      - "8081:8081"
    networks:
      - app-network

  word-service:
    build:
      context: .
      dockerfile: wordFilterService/Dockerfile
    # volumes:
    #   - ./wordFilterService:/app
    env_file:
      - wordFilterService/.env
    ports:
      - "8082:8082"
    networks:
      - app-network

  image-service:
    build:
      context: .
      dockerfile: imageCheck/Dockerfile
    env_file:
      - imageCheck/.env
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
